default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: Root@123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rocket

test:
  <<: *default
  database: rocket

production:
  <<: *default
  database: rocket